from argus.audit import references_section, split_entries, verdict

DOC = """Some introduction text.

Methods and results and discussion go here.

References
[1] Walters W. H. and Wilder E. I. (2023). Fabrication and errors in the
    bibliographic citations generated by ChatGPT. Scientific Reports 13, 14045.
[2] Day T. (2023). A Preliminary Investigation of Fake Peer-Reviewed Citations and
    References Generated by ChatGPT. The Professional Geographer 75, 1024-1027.
[3] Ji Z. et al. (2023). Survey of Hallucination in Natural Language Generation.

Appendix
Extra material that is not a reference.
"""


def test_references_section_isolated():
    section = references_section(DOC)
    assert "Walters" in section
    assert "Appendix" not in section
    assert "introduction" not in section


def test_split_numbered_entries():
    entries = split_entries(references_section(DOC))
    assert len(entries) == 3
    assert entries[0].startswith("Walters")
    assert "Day" in entries[1]


def test_verdict_match_and_no_match():
    entry = "Day T. 2023. A Preliminary Investigation of Fake Peer-Reviewed Citations."
    full = (
        "A Preliminary Investigation of Fake Peer-Reviewed Citations and "
        "References Generated by ChatGPT"
    )
    assert verdict(entry, full, ["Day"]) == "match"
    # title matches but the record's first author is absent from the entry
    short = "A Preliminary Investigation of Fake Peer-Reviewed Citations"
    assert verdict(entry, short, ["Nguyen"]) == "check"
    # nothing like the record in the entry
    assert verdict(entry, "Crystal structures of metal oxides", ["Navrotsky"]) == "no-match"


def test_references_section_survives_trailing_whitespace_blob():
    # Regression: a real .docx extraction ended in ~75 empty paragraphs (a 4.7k
    # whitespace run). With \s* padding in the heading regexes this backtracked
    # catastrophically and hung the CLI; the [ \t]* padding must stay linear.
    import time
    body = "Intro text [1].\n\nReferences\n\n[1] A. Author. A title. J. 2020.\n"
    blob = ("     \n" * 80) + (" " * 4000)
    t0 = time.time()
    section = references_section(body + blob)
    assert time.time() - t0 < 2.0
    assert "[1] A. Author" in section


def test_supplementary_references_heading_found():
    # A supplement titles its list "Supplementary References"; the whole document must not
    # be read as the bibliography.
    doc = ("Table S1. Data.\nGa-In 12 kJ/mol [1]\n\nSupplementary References\n"
           "1. Author A. A title. J 2020; 1: 1-2.\n2. Author B. Another. J 2021; 2: 3-4.\n")
    section = references_section(doc)
    assert section.lstrip().startswith("1. Author A")
    assert "Table S1" not in section
